name = "od"
type = "webpack"
workers_dev = true
account_id = "1c1a6880da0f1420e9e480f37ee333a6"
zone_id = "08a792f439c1f5ab2edb9cc359337afa"
kv_namespaces = [
    { binding = "BUCKET", id = "2288a0f1ed7f4accacddcf7079740716" }
]

[env.staging]
name = "drive-staging"
